# Generated by Django 3.1.5 on 2021-01-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('nit_cliente', models.CharField(max_length=20)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('c', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('existencias', models.IntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='detalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('Factura_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numfactura', to='todos.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='todos.producto')),
            ],
        ),
    ]
